<?php echo $this->doctype(); ?>

<html class="no-js" lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Interfase Digital'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/modernizr-2.6.2-respond-1.1.0.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div class="wrapper">
            <header class="container">
                <div class="col-md-4"></div>
                <div class="col-sm-8"></div>
            </header>
            <div class="container">
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; Company 2014</p>
                </footer>
            </div> <!-- /container -->
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
